- Dockerfile
- resources/Dockerfile@base
- resources/docker_entrypoint.sh
This simplifies the process of running Picus from Docker in the following ways:
* Slim down the docker image down to about 3GB (from >7GB?).
* Add `docker_entrypoint.sh` to make Picus easier to run on arbitrary code
* Simplify the docker build
Note that neither the base image nor the final image has been uploaded to DockerHub yet.
> Simplify Dockerfile running

- README.md
- picus-dpvl-uniqueness.rkt
Prior this commit, the counterexample output format is defaulted to r1cs signals (although the help page incorrectly says otherwise). This commit fixes the help page and at the same time switches the default format to circom variables, since the format is more readable for clients. The flag `--raw-output` can still be used to view the r1cs signals, which could be useful for debugging.
> Default the output format to circom variables

- picus/solvers/cvc5-solver.rkt
Since 368f3c3, cvc5 can produce a finite field literal, in the format:
```
#f <value> m <mod-value>
```
See https://github.com/cvc5/cvc5/commit/368f3c3ed695e925f0eea1b9d6a8280cdfa9f64c
This commit adds a support for finite field literal. It also refactors the existing model parsing to use S-expression reading that is already built-in to Racket.
> cvc5: support finite field literal

- README.md
- ansi.rkt
- picus-dpvl-uniqueness.rkt
- picus/algorithms/dpvl.rkt
This commit adds a flag `--verbose` for verbose level, which supplants the flag `--raw-output` (or, previously, `--map`).
- When the verbose level is 0 (not verbose), the output is in the circom variable format.
- When the verbose level is 1, the output is a mixed between the circom variable format and the r1cs signal format, where we prefer the circom variable format whenever possible.
- When the verbose level is 2, the output is always in the r1cs signal format.
For `--verbose 0`, the output now has three sections: inputs, first possible outputs, and second possible outputs.
For other verbosity level, there could be four sections. The extra section is "other bindings".
Entries that are different in the first possible outputs and second possible outputs are further highlighted with ANSI …
> Restructure counterexample output format for readability

- .github/workflows/docker-image.yml
- Prior this commit, every job depends on `publish-docker`, which is only
run on push. Therefore, all jobs are skipped. This commit fixes the
issue by removing the dependency.
- `publish-docker` is now also run as the last step, only when all tests passed.
- All subsequent jobs are now run on veridise/picus:git-latest,
so that we do not need to push first.
- The tests are slightly more sophisticated. Previously, it only ensures
that there's no error. Now, we also check against expected
output (underconstrained or not).
- Switch to use Racket and Rosette that are already installed in the
image. It turns out that we need to set the environment variable
`PLTADDONDIR` for this to work, because $HOME is overriden in containers
in GHA (https://github.com/actions/runner/issues/863).
- Remove a …
> ci: run ci on pull_request and add basic tests

- picus/solvers/cvc4-solver.rkt
- picus/solvers/cvc5-solver.rkt
- picus/solvers/z3-solver.rkt
On benchmarks that are not quickly solved, I keep encountering the error:
subprocess: process creation failed
system error: Too many open files; errno=24
This is because ports are not properly closed when the corresponding process is killed. This commit fixes the problem.
In the long run, it would be better to restructure these modules to share common code, so that the fix can be done at a single place.
> solvers: close ports properly

- .github/workflows/docker-image.yml
- .gitignore
- picus/r1cs/r1cs-grammar.rkt
- tests/efficient-parsing.rkt
Prior this commit, `read-r1cs` copied bytes in the file over and over again in a hot loop, causing the time complexity to be quadratic. This commit switches to use index-based access in the hot loop instead, resulting in a large performance improvement.
The benchmark file that accompanies this fix took 30 minutes to successfully parse (according to @shankarapailoor). This commit reduces the parsing time to 2 seconds.
It should be noted that not all bytes copying is avoided, since bytes copying outside the hot loop, although not ideal, does not really impact the performance.
> fix: make parser significantly more efficient

- picus.rkt
- picus/algorithms/dpvl.rkt
- verbose.rkt
This commit renames the existing --verbose to --cex-verbose, and makes --verbose control the non-counterexample output, which could be overwhelming on a very large circuit. Similar to --cex-verbose, there are three levels for --verbose.
- 0: hides "large" outputs entirely.
- 1: shows the output, but display ... when the output is too large
- 2: shows the full output.
> feat: support --verbose and --cex-verbose

- picus/algorithms/dpvl.rkt
Instead of using list-ref in a loop (which takes quadratic time) and list membership in a loop (which also takes quadratic time), switch to direct element iteration and set membership query. This reduces the running time on the large benchmark from >10mins (I haven't fully measured it. Terminated it early because I don't want to wait) to 0.6s.
> fix: make known set computation more efficient

- picus/algorithms/lemmas/basis2-lemma.rkt
In basis2 lemma, set-remove (which removes a single element) is used instead of set-subtract (which removes a set of elements). Previously, Picus gets away with this incorrect result because linear lemma will "clean up" afterward by syncing known set and unknown set. However, in the PR #18, we no longer do this syncing, thus uncovering this issue. This commit fixes the problem.
> fix: compute unknown set correctly

- picus/algorithms/dpvl.rkt
- picus/algorithms/lemmas/linear-lemma.rkt
- picus/algorithms/selectors/counter-selector.rkt
Prior this commit, linear lemma depends on the CDMAP and RCDMAP procedures.
Let's say that constraint i involves variables Xi and Yi, where Xi variables are the linear part, and Yi variables are the non-linear parts. That is to say, the input follows this format:
Constraint 1: X11 X12 ... Y11 Y12 ...
Constraint 2: X21 X22 ... Y21 Y22 ...
...
Constraint n: Xn1 Xn2 ... Yn1 Yn2 ...
which is of size O(sum |Xi| + sum |Yi|).
The CDMAP procedure produces a map from a variable to a list of list of variables. Meaning: a key can be uniquely determined if one of the list of variables are all uniquely determined.
Thus, CDMAP produces a data of size O(sum { |Xi| (|Xi| + |Yi|) }) as the output (where values of the same key are grouped together)
X11: X12 X13 ... Y11 Y12 ...
X12: X11 X13 ... Y11 Y12 ... …
> fix: reimplement linear lemma to make it more efficient

- picus/algorithms/lemmas/bim-lemma.rkt
This is done by switching list-ref in a loop to direct iteration. Also fix a typo that labels the pass from "aboz" to "bim".
> fix: make bim lemma more efficient

- picus/algorithms/dpvl.rkt
Use vector indexing instead of list indexing.
This avoids cost to list traversal, which is significant in a hot loop.
> fix: make query generation more efficient

- picus/algorithms/dpvl.rkt
- picus/r1cs/common.rkt
- picus/r1cs/r1cs-cvc4-interpreter.rkt
- picus/r1cs/r1cs-cvc5-interpreter.rkt
- picus/r1cs/r1cs-z3-interpreter.rkt
- picus/tokamak.rkt
We should avoid building the resulting query string with `format` repeatedly, because `format` creates an entirely new string in each invocation. When the query is big, the cost is prohibitively expensive.
This commit instead builds the query string by writing to a string port directly (similar to the StringBuilder idiom in languages like Java). As the fix needs to be done on Z3, cvc4, and cvc5, I also take an opportunity to refactor them to reduce code redundancy.
> fix: make printer for query generation more efficient

- tests/circomlib-test.rkt
The markup ##[...] makes GHA groups outputs together, making it easy to compare results across runs.
> ci: improve the output

- picus/r1cs/r1cs-grammar.rkt
Prior this commit, the variables are repeatedly appended at the back of a list, causing quadratic running time. Since ordering doesn't matter, this commit makes it appends to the front instead.
Note that the algorithm overall is still potentially quadratic. A proper fix needs to changes the interface significantly to introduce an additional accumulator. This commit simply makes a minimal fix for the immediate issue that we are having,
which causes CompConstant to get stuck.
> fix: speed up variable extractions

- .github/workflows/docker-image.yml
- .gitignore
- picus/public-inputs.rkt
- picus/solvers/common.rkt
- tests/circomlib-test.rkt
Prior this commit, we cannot write tests expecting a timeout. This commit adds the ability to do so.
Another major change is to support tests with optimization flag. When Circom is given -O2, Circom files without public inputs (which are all of our benchmarks) will fail to be compiled correctly. This commit adds a heustistic to detect such situation, and then "patch" the Circom file to add public inputs. This is done by doing Circom compilation twice.
The first compilation allows us to read information from R1CS file, which is then used for patching. The second compilation compiles the patched file.
> ci: support timing out and optimization flag

- .github/workflows/docker-image.yml
- picus.rkt
This commit adds a capability to process circom files directly via the `--circom` flag. This is done by creating a temporary directory to store the compiled r1cs file. The temporary directory is cleaned up on exit when Picus exits normally. However, when Picus crashes or when it is interrupted, the temporary directory will not be cleaned, giving the user an opportunity to inspect files.
Additionally, `--opt-level` can be used to specify optimization level for circom compilation.
> feat: support processing circom file directly

- picus.rkt
- picus/solvers/common.rkt
- picus/tmpdir.rkt
Previously, Picus never cleans up smt2 files, and put them all in the top-level temporary directory, causing it to be cluttered with many Picus files.
This commit puts the generated smt2 files in a proper per-run temporary directory (introduced in #33), which by default will also get deleted afterward.
A separate commit adds an ability to retain the temporary files via `--noclean` in case the user wants to see the generated smt2 files for debugging purposes.
> Use temporary directory more effectively

- .gitignore
- picus.rkt
- picus/global-inputs.rkt
- tests/circomlib-test.rkt
This PR consists of two commits.
- The first commit adds the patching feature properly via `--patch-circom`.
- The second commit switches the current tests to use this new flag.
> feat: support patching properly

- picus/tmpdir.rkt
It could be that tmpdir is never created, particularly in the --r1cs mode (so there is no circom compilation which requires tmpdir), and under the situation where propagation suffices for determining safety (so no need to call the solver => no need to create the smt2 file in the tmpdir). In such case, tmpdir is false, so Picus fails with a contract error. This commit fixes the problem.
> fix: only remove tmpdir when tmpdir actually is created

- .github/workflows/docker-image.yml
- picus.rkt
- picus/algorithms/dpvl.rkt
- picus/algorithms/lemmas/aboz-lemma.rkt
- picus/algorithms/lemmas/baby-lemma.rkt
- picus/algorithms/lemmas/basis2-lemma.rkt
- picus/algorithms/lemmas/bim-lemma.rkt
- picus/algorithms/lemmas/binary01-lemma.rkt
- picus/algorithms/lemmas/linear-lemma.rkt
- tests/circomlib-test.rkt
Make --verbose 0 not output algorithm computation. Also remove the leading "#" in the output
> chore: adjust behavior of no verbose

- tests/circomlib-test.rkt
This would have caught the mistake fixed in #38
> ci: additionally check that Picus terminates properly

- .github/workflows/docker-image.yml
- README.md
- picus-solve.sh
- picus.rkt
- scripts/batch-run-picus-noprop.sh
- scripts/batch-run-picus-nosolve.sh
- scripts/batch-run-picus-pre.sh
- scripts/batch-run-picus.sh
- tests/circomlib-test.rkt
We almost always only want the weak safety (checking that output signals of the main component are deterministic), not strong safety (checking that all signals are deterministic). However, currently the strong safety mode is the default. This makes it cumbersome to invoke Picus, since we need to indicate that we want the weak safety explicitly.
This commit inverts the behavior by removing the flag `--weak` and adds the flag `--strong` (for strong safety), which is defaulted to false.
> Make --weak the default

- .github/workflows/docker-image.yml
- tests/circomlib-test.rkt
This commit adds a flag `--parallel <id> <num>` to the test script. This divides the tests into `<num>` parts, and the script will only run the `<id>`-th part.
> ci: parallelize tests on GHA

- .github/workflows/docker-image.yml
Refactor the ad-hoc tests in GHA to reduce code duplication and makes the tests easier to extend.
> ci: unify configuration tests

- .github/workflows/docker-image.yml
- picus/exit.rkt
- picus/framework.rkt
- picus/logging.rkt
- tests/framework-test.rkt
This commit adds a framework for logging and exiting in a way that conforms to the SaaS requirement. Logging in particular could be done in either the JSON mode or the text mode.
The main entry point to the framework is the `with-framework` function.
This commit does not yet switch Picus to use the framework. That will be done in a separate commit.
See `framework-test.rkt` for tests of the framework.
> feat: framework for SaaS

- .dockerignore
- Dockerfile
When built locally, Picus often fails to run due to the mismatch of the compiled files in the newer, local Racket version, and the older, image-based Racket version. This commit fixes the issue.
> docker: build compiled files

- .github/workflows/docker-base.yml
- .github/workflows/docker-image.yml
CoCoA wasn't successfully compiled on arm64 for some reasons. See
https://github.com/Veridise/Picus/actions/runs/6483965862/job/17606717211#step:4:15460. So we disable arm64 target for now.
> ci: only run amd64 for now

- .dockerignore
This should help making the Docker image a bit smaller.
> docker: do not copy benchmarks dir
